Disable doctest to get rid of allocator message
Having them activated causes this message:
error: no global memory allocator found but one is required; link to
std or add #[global_allocator] to a static item that implements the
GlobalAlloc trait.

The tests still succeed, but it's annoying. Therefore disabled until
we have any doctests.

https://github.com/rust-lang/rust/issues/54010